version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb listings.
    columns:
      - name: listing_id
        description: Primary key for the listing
        tests:
          - unique:
              name: test4
          - not_null:
              name: test5

      - name: host_id
        description: The hosts id references the host table
        tests:
          - not_null:
              name: test2
          - relationships:
              name: test3
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        description: Type of the apartment / room
        tests:
          - accepted_values:
              name: test1
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]

      - name: minimum_nights
        description: '{{ doc("dim_listing_cleansed_minimum_nights") }}'
        tests:
          - positive_value
