version: 2

models:
  - name: dim_listings_cleansed
    columns:
      - name: listing_id
        tests:
          - unique:
              name: test4
          - not_null:
              name: test5

      - name: host_id
        tests:
          - not_null:
              name: test2
          - relationships:
              name: test3
              to: ref('dim_hosts_cleansed')
              field: host_id

      - name: room_type
        tests:
          - accepted_values:
              name: test1
              values:
                ["Entire home/apt", "Private room", "Shared room", "Hotel room"]

      - name: minimum_nights
        tests:
          - positive_value
