airbnb_dbt:
  outputs:
    dev:
      account: {{ secrets.ACCOUNT }}
      database: AIRBNB
      password: {{ secrets.PASSWORD }}
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: {{ secrets.USER }}
      warehouse: COMPUTE_WH
  target: dev
