airbnb_dbt:
  outputs:
    dev:
      account: $ACCOUNT
      database: AIRBNB
      password: $PASSWORD
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: $USER
      warehouse: COMPUTE_WH
  target: dev
