airbnb_dbt:
  outputs:
    dev:
      account: "{{ env_var('ACCOUNT') }}"
      database: AIRBNB
      password: "{{ env_var('PASSWORD) }}"
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: "{{ env_var('USER') }}"
      warehouse: COMPUTE_WH
  target: dev
